import Foundation

/// A Feature-owned file containing native AppShortcut builder expressions.
/// The file is compiled into the app's provider, not interpreted at runtime.
public struct FeatureAppShortcuts: Sendable {
    public let owner: String
    public let imports: [String]
    public let sourceFile: String

    public init(owner: String, imports: [String], sourceFile: String) {
        self.owner = owner
        self.imports = imports
        self.sourceFile = sourceFile
    }

    public enum Failure: Error {
        case duplicateOrEmptyOwner(String)
        case emptySource(String)
    }

    /// Replaces exactly one generated file after all inputs have been read.
    /// With no contributions, writes no provider and removes stale definitions.
    public static func writeProvider(_ features: [Self], to destination: String) throws {
        var owners = Set<String>()
        var modules: Set<String> = ["AppIntents"]
        var bodies: [String] = []
        for feature in features {
            guard !feature.owner.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
                  owners.insert(feature.owner).inserted else {
                throw Failure.duplicateOrEmptyOwner(feature.owner)
            }
            let path = URL(fileURLWithPath: feature.sourceFile).standardizedFileURL.path
            let source = try String(contentsOfFile: path, encoding: .utf8)
            guard !source.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
                throw Failure.emptySource(feature.owner)
            }
            modules.formUnion(feature.imports)
            bodies.append("#sourceLocation(file: \(String(reflecting: path)), line: 1)\n"
                + source + "\n#sourceLocation()")
        }
        var output = "// Generated by FeatureAppShortcuts; edit the Feature source files.\n"
        if !features.isEmpty {
            output += modules.sorted().map { "import \($0)\n" }.joined()
            output += "\nstruct JibunKitAppShortcuts: AppShortcutsProvider {\n"
                + "    static var appShortcuts: [AppShortcut] {\n"
                + bodies.joined(separator: "\n") + "\n    }\n}\n"
        }
        let target = URL(fileURLWithPath: destination)
        try FileManager.default.createDirectory(at: target.deletingLastPathComponent(), withIntermediateDirectories: true)
        try output.write(to: target, atomically: true, encoding: .utf8)
    }
}
