// Generated by `python3 Tools/jibunkit-feature.py sync` from Modules/*/JibunKitFeature.json.
// Do not edit; change the Feature's JibunKitFeature.json and run sync again.
import ProjectDescription

public enum ModuleFeatures {
    public static let all: [ModuleFeature] = [
    ]
}
